shared:
  foo: "foo value"
  bar: "bar value"
  symbol: "symbol_value"
  int: "1"
  float: "1.1"
  bool: "true"
  time: "2023-05-25-19:06Z"
  array: [1, 2, 3]
  specific_key: "specific value"
  all_enabled: "yaml value"
  all_disabled: "not yaml value"

test:
  bar: "test value"
